// @ts-check
import path from 'node:path';

/** @param {string} s */
const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const rich = (/** @type {string} */ s) => esc(s).replace(/`([^`]+)`/g, '<code>$1</code>');

const ICON = { pass: '✓', fail: '✗', timeout: '✗', skip: '–' };

/**
 * Self-contained HTML report (no external requests), light/dark aware.
 * @param {import('../check.js').Report} report
 * @param {string} relFile
 */
export function toHTML(report, relFile) {
  const { passed, failed, skipped, durationMs } = report.summary;
  const ok = failed === 0 && passed > 0;
  const rows = report.entries
    .map(({ step, result, diagnoses }) => {
      const status = result.status === 'timeout' ? 'fail' : result.status;
      const diag = diagnoses
        .map((d) => `<li><strong>${rich(d.message)}</strong>${d.fix ? `<div class="fix">Fix: ${rich(d.fix)}</div>` : ''}</li>`)
        .join('');
      const reasons = result.failures.map((f) => `<div class="reason">${esc(f)}</div>`).join('');
      const output = result.status === 'pass' || result.status === 'skip' ? '' : `<pre>${esc(result.output.trimEnd().split('\n').slice(-40).join('\n'))}</pre>`;
      return `<section class="step ${status}">
  <header><span class="icon">${ICON[result.status]}</span><code>${esc(step.label)}</code><span class="meta">line ${step.line}${result.status === 'skip' ? '' : ` · ${result.durationMs} ms`}</span></header>
  ${result.status === 'skip' ? `<div class="reason muted">${esc(result.failures[0] ?? 'skipped')}</div>` : reasons}
  ${output}${diag ? `<ul class="diag">${diag}</ul>` : ''}
</section>`;
    })
    .join('\n');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>freshclone report: ${esc(path.basename(relFile))}</title>
<style>
:root{--bg:#fff;--fg:#1f2328;--muted:#656d76;--card:#f6f8fa;--line:#d0d7de;--ok:#1a7f37;--bad:#cf222e;--warn:#9a6700;--accent:#0969da}
@media (prefers-color-scheme:dark){:root{--bg:#0d1117;--fg:#e6edf3;--muted:#8d96a0;--card:#161b22;--line:#30363d;--ok:#3fb950;--bad:#f85149;--warn:#d29922;--accent:#58a6ff}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif}
main{max-width:860px;margin:0 auto;padding:32px 16px 64px}
h1{font-size:20px;margin:0 0 4px}.sub{color:var(--muted);margin:0 0 20px}
.verdict{padding:14px 16px;border-radius:8px;border:1px solid var(--line);background:var(--card);margin-bottom:24px;font-weight:600;border-left:4px solid ${ok ? 'var(--ok)' : failed ? 'var(--bad)' : 'var(--warn)'}}
.verdict small{display:block;font-weight:400;color:var(--muted)}
.step{border:1px solid var(--line);border-radius:8px;margin-bottom:10px;padding:10px 14px;background:var(--card);border-left:4px solid var(--line)}
.step.pass{border-left-color:var(--ok)}.step.fail{border-left-color:var(--bad)}.step.skip{border-left-color:var(--warn)}
.step header{display:flex;gap:10px;align-items:baseline;flex-wrap:wrap}
.icon{font-weight:700;width:1em}.pass .icon{color:var(--ok)}.fail .icon{color:var(--bad)}.skip .icon{color:var(--warn)}
code,pre{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:13px}
.meta{margin-left:auto;color:var(--muted);font-size:12px}
.reason{color:var(--bad);margin-top:6px;font-size:13px}.reason.muted{color:var(--muted)}
pre{background:var(--bg);border:1px solid var(--line);border-radius:6px;padding:10px;overflow:auto;margin:8px 0 0;white-space:pre-wrap;word-break:break-word}
.diag{margin:10px 0 0;padding-left:18px}.diag li{margin-bottom:6px}.fix{color:var(--muted);font-size:13px}
footer{color:var(--muted);font-size:12px;margin-top:28px}
</style></head><body><main>
<h1>freshclone report</h1>
<p class="sub"><code>${esc(relFile)}</code> · ${report.room.files} files in a clean room, empty HOME, scrubbed environment</p>
<div class="verdict">${ok ? 'This README works from a fresh clone.' : failed ? 'This README does not work from a fresh clone.' : 'Nothing to run.'}<small>${passed} passed · ${failed} failed · ${skipped} skipped · ${(durationMs / 1000).toFixed(1)}s</small></div>
${rows}
<footer>Generated by <a href="https://github.com/Nithinfgs/freshclone">freshclone</a>.</footer>
</main></body></html>
`;
}
